services:
  proxy:
    image: ${NGINX_VERSION}
    networks:
      - lemmyinternal
      - lemmyexternalproxy
    ports:
      - ${EXTERNAL_PORT}:80
    volumes:
      # These two volumes are needed for nginx.conf to support environment variables, do not change them
      - ./.nginx.helper:/etc/nginx/nginx.conf:ro
      - ./nginx.conf:/etc/nginx/templates/nginx.conf.template
    restart: always
    environment:
      - SERVER_NAME:${LEMMY_UI_LEMMY_EXTERNAL_HOST}
    depends_on:
      - pictrs
      - lemmy-ui
      - lemmy

  lemmy:
    image: ${DESSALINES_LEMMY_VERSION}
    hostname: lemmy
    networks:
      - lemmyinternal
    restart: always
    environment:
      - RUST_LOG="warn,lemmy_server=info,lemmy_api=info,lemmy_api_common=info,lemmy_api_crud=info,lemmy_apub=info,lemmy_db_schema=info,lemmy_db_views=info,lemmy_db_views_actor=info,lemmy_db_views_moderator=info,lemmy_routes=info,lemmy_utils=info,lemmy_websocket=info"
    volumes:
      - ./lemmy.hjson:/config/config.hjson
    depends_on:
      - postgres
      - pictrs

  lemmy-ui:
    image: ${DESSALINES_LEMMY_UI_VERSION}
    networks:
      - lemmyinternal
    environment:
      # this needs to match the hostname defined in the lemmy service
      - LEMMY_UI_LEMMY_INTERNAL_HOST=lemmy:8536
      # set the outside hostname here
      - LEMMY_UI_LEMMY_EXTERNAL_HOST=${LEMMY_UI_LEMMY_EXTERNAL_HOST}:1236
      - LEMMY_HTTPS=true
    depends_on:
      - lemmy
    restart: always

  pictrs:
    image: ${ASONIX_PICTRS_VERSION}
    # this needs to match the pictrs url in lemmy.hjson
    hostname: pictrs
    # we can set options to pictrs like this, here we set max. image size and forced format for conversion
    # entrypoint: /sbin/tini -- /usr/local/bin/pict-rs -p /mnt -m 4 --image-format webp
    networks:
      - lemmyinternal
    environment:
      - PICTRS__API_KEY=API_KEY
    user: 991:991
    volumes:
      - ./volumes/pictrs:/mnt
    restart: always

  postgres:
    image: ${POSTGRES_VERSION}
    # this needs to match the database host in lemmy.hson
    hostname: postgres
    networks:
      - lemmyinternal
    environment:
      - POSTGRES_USER=lemmy
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=lemmy
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    restart: always

networks:
  # communication to web and clients
  lemmyexternalproxy:
  lemmyinternal:
    driver: bridge

# This section limits the amount of storage used by log files avoiding future crashes...
x-logging: 
  &default-logging
  driver: "json-file"
  options:
    max-size: "50m"
    max-file: 4
